use super::TemplateFile;
use super::{GITIGNORE, ENV_EXAMPLE};

const PACKAGE_JSON: &str = r#"{
  "name": "{{name}}",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^16.2.7",
    "react": "^19.2.7",
    "react-dom": "^19.2.7"
  },
  "devDependencies": {
    "@types/node": "^25.9.1",
    "@types/react": "^19.2.16",
    "@types/react-dom": "^19.2.3",
    "typescript": "^6.0.3",
    "tailwindcss": "^4.3.0",
    "autoprefixer": "^10.5.0"
  }
}"#;

const NEXT_CONFIG: &str = r#"import type { NextConfig } from 'next'

const nextConfig: NextConfig = {}

export default nextConfig"#;

const TSCONFIG: &str = r#"{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["DOM", "DOM.Iterable", "ES2020"],
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "preserve",
    "strict": true,
    "skipLibCheck": true,
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}"#;

const TAILWIND_CONFIG: &str = r#"import type { Config } from 'tailwindcss'

export default {
  content: [
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
} satisfies Config"#;


const LAYOUT_TSX: &str = r#"import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '{{name}}',
  description: 'Generated by zila',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}"#;

const PAGE_TSX: &str = r#"export default function Home() {
  return (
    <main className="min-h-screen bg-white">
      <h1 className="text-2xl font-bold">Hello from zila 🦀</h1>
    </main>
  )
}"#;

const GLOBALS_CSS: &str = r#"@tailwind base;
@tailwind components;
@tailwind utilities;"#;

const DEVCONTAINER: &str = r#"{
  "name": "{{name}}",
  "image": "mcr.microsoft.com/devcontainers/typescript-node:22",
  "forwardPorts": [3000],
  "postCreateCommand": "npm install",
  "customizations": {
    "vscode": {
      "extensions": [
        "dbaeumer.vscode-eslint",
        "bradlc.vscode-tailwindcss"
      ]
    }
  }
}"#;

pub fn files() -> Vec<TemplateFile> {
    vec![
        TemplateFile { path: "package.json",                    content: PACKAGE_JSON   },
        TemplateFile { path: "next.config.ts",                  content: NEXT_CONFIG    },
        TemplateFile { path: "tsconfig.json",                   content: TSCONFIG       },
        TemplateFile { path: "tailwind.config.ts",              content: TAILWIND_CONFIG},
        TemplateFile { path: "src/app/layout.tsx",              content: LAYOUT_TSX     },
        TemplateFile { path: "src/app/page.tsx",                content: PAGE_TSX       },
        TemplateFile { path: "src/app/globals.css",             content: GLOBALS_CSS    },
        TemplateFile { path: ".gitignore",                      content: GITIGNORE      },
        TemplateFile { path: ".env.example",                    content: ENV_EXAMPLE    },
        TemplateFile { path: ".devcontainer/devcontainer.json", content: DEVCONTAINER   },
    ]
}
